title: Tanvi Gawade # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a graduate student at California State University, Los Angeles and soon be graduating in May 2020 . I love to explore the relationships between numbers and translate digits into meaningful stories, analyze trends/patterns as well as interpret data with a clear objective in mind.
  I am passionate about data analytics and love to identify new data sources/sets to mine & apply my analytical skills making a true impact.
  <br><br>
  <a href="https://www.linkedin.com/in/tanvigawade/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-1623059821-1 # your Google Analytics tracking ID here
